package org.awsCognito.commons;

/*
 * This Class is used to decode the otp generated by lambda trigger.
 * 
 * author @pavan
 * 
 * user data can be changed from application.properties file from the classpath
 * 
 */

import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.Duration;

import com.bastiaanjansen.otp.TOTP;
import com.bastiaanjansen.otp.TOTP.Builder;

public class OTP {
	
	public static void main(String [] args) {
		
		String secret = "R5D6K7H4XBKTTYMECCP4BE5FXHE24VR4";
		System.out.println(getOTP(secret));
	}

	public static String getOTP(String otp_hash) {
		
		byte[] secret = otp_hash.getBytes();
		
		Builder builder = new TOTP.Builder(secret);
		
		TOTP totp = builder.withPeriod(Duration.ofSeconds(300)).build();
		
		try {
		    String code = totp.now();
		    return code;
		} catch (IllegalStateException e) {
		    // Handle error
		}
		return null;
	}

}
